default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  port: 5432
  host: <%= ENV['DATABASE_HOST'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: open_flights_development

test:
  <<: *default
  database: open_flights_test

production:
  <<: *default
  database: open_flights_production
  username: open_flights
  password: <%= ENV['OPEN_FLIGHTS_DATABASE_PASSWORD'] %>
